cmake_minimum_required(VERSION "3.16")
project(dictionaries)
set(OpenCV_DIR /usr/local/include/opencv4)
set(CMAKE_CXX_STANDARD 14)
find_package( OpenCV REQUIRED )
include_directories( ${OpenCV_INCLUDE_DIRS} )
add_executable(dictionaries try.cpp)
target_link_libraries(dictionaries ${OpenCV_LIBS} )

